use std::path::Path;

const DEFAULT_GETHE_WOW_UI_SOURCE_BRANCHES: &[&str] = &[
    "live",
    "beta",
    "classic",
    "classic_era",
    "classic_anniversary",
    "classic_beta",
    "classic_ptr",
];

const MISTS_GETHE_WOW_UI_SOURCE_BRANCHES: &[&str] = &[
    "classic_ptr",
    "classic_anniversary",
    "classic_beta",
    "classic",
    "classic_era",
    "live",
    "beta",
];

pub(super) const MISTS_REQUIRED_PROFILE_CACHE_ENTRIES: &[&str] = &[
    "Blizzard_ActionBar/Classic/ActionButtonTemplate.xml",
    "Blizzard_ActionBar/Classic/ActionButtonUtilOverrides.lua",
    "Blizzard_ActionBar/Classic/ExpBar.xml",
    "Blizzard_ActionBar/Classic/ExpBarOverrides.lua",
    "Blizzard_ActionBar/Classic/MainActionBar.xml",
    "Blizzard_ActionBar/Classic/MainActionBarOverrides.lua",
    "Blizzard_ActionBar/Classic/MainMenuBar.lua",
    "Blizzard_ActionBar/Classic/MainMenuBar.xml",
    "Blizzard_ActionBar/Classic/PetActionBar.xml",
    "Blizzard_ActionBar/Classic/PossessActionBar.xml",
    "Blizzard_ActionBar/Classic/ReputationBarOverrides.lua",
    "Blizzard_ActionBar/Classic/StanceBar.xml",
    "Blizzard_ActionBar/Classic/StanceBarOverrides.lua",
    "Blizzard_ActionBar/Classic/StatusTrackingBar.xml",
    "Blizzard_ActionBar/Classic/StatusTrackingBarTemplate.xml",
    "Blizzard_ActionBar/Classic/StatusTrackingManagerOverrides.lua",
    "Blizzard_ChatFrameBase/Blizzard_ChatFrameBase_Classic.toc",
    "Blizzard_ChatFrameBase/Classic/ChannelFrameButtonMixin.lua",
    "Blizzard_ChatFrameBase/Classic/ChatEmoteConstants.lua",
    "Blizzard_ChatFrameBase/Classic/ChatFrame.xml",
    "Blizzard_ChatFrameBase/Classic/ChatFrameEditBox.xml",
    "Blizzard_ChatFrameBase/Classic/ChatFrameEditBoxOverrides.lua",
    "Blizzard_ChatFrameBase/Classic/ChatFrameMenuButton.lua",
    "Blizzard_ChatFrameBase/Classic/ChatFrameOverrides.lua",
    "Blizzard_ChatFrameBase/Classic/ChatFrameUtilOverrides.lua",
    "Blizzard_ChatFrameBase/Classic/ChatTypeInfoConstantsOverride.lua",
    "Blizzard_ChatFrameBase/Classic/FloatingChatFrame.lua",
    "Blizzard_ChatFrameBase/Classic/FloatingChatFrame.xml",
    "Blizzard_ChatFrameBase/Classic/FriendFrameButtonMixin.lua",
    "Blizzard_ChatFrameBase/Classic/SlashCommandsOverrides.lua",
    "Blizzard_ChatFrameBase/Shared/ChatFrameUtil.lua",
    "Blizzard_FrameXMLUtil/Blizzard_FrameXMLUtil_Classic.toc",
    "Blizzard_FrameXMLUtil/Classic/ArenaUtil.lua",
    "Blizzard_FrameXMLUtil/Classic/AuraUtil.lua",
    "Blizzard_FrameXMLUtil/Classic/Cooldown.xml",
    "Blizzard_FrameXMLUtil/Classic/MapUtil.lua",
    "Blizzard_FrameXMLUtil/Classic/QuestUtils.lua",
    "Blizzard_FrameXMLUtil/Classic/RaidWarning.lua",
    "Blizzard_FrameXMLUtil/Classic/TransmogUtil.lua",
    "Blizzard_ObjectAPI/Blizzard_ObjectAPI_Classic.toc",
    "Blizzard_ObjectAPI/Classic/ContinuableContainer.lua",
    "Blizzard_ObjectAPI/Classic/Item.lua",
    "Blizzard_ObjectAPI/Classic/ItemLocation.lua",
    "Blizzard_ObjectAPI/Classic/PlayerLocation.lua",
    "Blizzard_ObjectAPI/Classic/Spell.lua",
    "Blizzard_FrameXML/TBC/WorldStateFrame.lua",
    "Blizzard_MainMenuBarBagButtons/Classic/MainMenuBarBagButtons.lua",
    "Blizzard_MicroMenu/Blizzard_MicroMenu_Classic.toc",
    "Blizzard_MicroMenu/Shared/MicroMenuContainer.lua",
    "Blizzard_SettingsDefinitions_Frame/Blizzard_SettingsDefinitions_Frame_Classic.toc",
    "Blizzard_SettingsDefinitions_Frame/Classic/AccessibilityOverrides.lua",
    "Blizzard_SettingsDefinitions_Frame/Classic/Colorblind.xml",
    "Blizzard_SettingsDefinitions_Frame/Classic/ColorblindOverrides.lua",
    "Blizzard_SettingsDefinitions_Frame/Classic/CombatOverrides.lua",
    "Blizzard_SettingsDefinitions_Frame/Classic/ControlsOverrides.lua",
    "Blizzard_SettingsDefinitions_Frame/Classic/GameplaySettingsGroup.lua",
    "Blizzard_SettingsDefinitions_Frame/Classic/InterfaceOverrides.lua",
    "Blizzard_SettingsDefinitions_Frame/Classic/KeybindingsOverrides.lua",
    "Blizzard_SettingsDefinitions_Frame/Classic/SocialOverrides.lua",
    "Blizzard_SettingsDefinitions_Frame/CombatAudioAlertUtil.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgets.toc",
    "Blizzard_UIWidgets/Blizzard_UIWidgetAnimationTemplates.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetAnimationTemplates.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetBelowMinimapFrame.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetBelowMinimapFrame.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetCenterScreenFrame.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetCenterScreenFrame.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetManager.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetManager.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBase.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBulletTextList.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateBulletTextList.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateButtonHeader.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateButtonHeader.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateCaptureBar.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateCaptureBar.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateCaptureZone.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateCaptureZone.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDiscreteProgressSteps.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDiscreteProgressSteps.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDoubleIconAndText.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDoubleIconAndText.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDoubleStateIconRow.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDoubleStateIconRow.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDoubleStatusBar.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateDoubleStatusBar.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateFillUpFrames.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateFillUpFrames.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateHorizontalCurrencies.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateHorizontalCurrencies.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateIconAndText.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateIconAndText.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateIconTextAndBackground.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateIconTextAndBackground.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateIconTextAndCurrencies.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateIconTextAndCurrencies.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateItemDisplay.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateItemDisplay.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateMapPinAnimation.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateMapPinAnimation.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplatePreyHuntProgress.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplatePreyHuntProgress.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateScenarioHeaderCurrenciesAndBackground.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateScenarioHeaderCurrenciesAndBackground.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateScenarioHeaderDelves.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateScenarioHeaderDelves.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateScenarioHeaderTimer.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateScenarioHeaderTimer.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateSpacer.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateSpacer.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateSpellDisplay.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateSpellDisplay.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateStackedResourceTracker.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateStackedResourceTracker.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateStatusBar.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateStatusBar.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextColumnRow.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextColumnRow.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextWithState.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextWithState.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextWithSubtext.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextWithSubtext.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextureAndText.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextureAndText.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextureAndTextRow.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextureAndTextRow.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextureWithAnimation.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTextureWithAnimation.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTugOfWar.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateTugOfWar.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateUnitPowerBar.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateUnitPowerBar.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateZoneControl.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTemplateZoneControl.xml",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTopCenterFrame.lua",
    "Blizzard_UIWidgets/Blizzard_UIWidgetTopCenterFrame.xml",
    "Blizzard_UIWidgets/Blizzard_WidgetsUtil.lua",
    "Blizzard_SharedXML/Classic/ClassicCvarUtil.lua",
    "Blizzard_SharedXML/Classic/Dialog/DialogTemplates.xml",
    "Blizzard_SharedXML/Classic/Frame/MainMenuFrameTemplates.xml",
    "Blizzard_SharedXML/Classic/GameTooltipTemplate.xml",
    "Blizzard_SharedXML/Classic/GlueCheck.lua",
    "Blizzard_SharedXML/Classic/ModelFrames.lua",
    "Blizzard_SharedXML/Classic/ModelFrames.xml",
    "Blizzard_SharedXML/Classic/NineSliceLayouts.lua",
    "Blizzard_SharedXML/Classic/Scroll/TrimScrollBar.xml",
    "Blizzard_SharedXML/Classic/ScrollDefine.lua",
    "Blizzard_SharedXML/Classic/ScrollDefine.xml",
    "Blizzard_SharedXML/Classic/SecureCurrencyUtil.lua",
    "Blizzard_SharedXML/Classic/Selector/Blizzard_ScrollBoxSelector.xml",
    "Blizzard_SharedXML/Classic/SharedUIPanelTemplates.lua",
    "Blizzard_SharedXML/Classic/SharedUIPanelTemplates.xml",
    "Blizzard_SharedXML/Classic/SharedUtils.lua",
    "Blizzard_SharedXML/Classic/SliderTemplates.xml",
    "Blizzard_SharedXML/Classic/Sound.lua",
    "Blizzard_SharedXML/Classic/Stubs.lua",
    "Blizzard_SharedXML/Classic/Stubs.xml",
    "Blizzard_SharedXML/Classic/UIDropDownMenu.lua",
    "Blizzard_SharedXML/Classic/UIDropDownMenu.xml",
    "Blizzard_SharedXML/Classic/UIDropDownMenuTemplates.lua",
    "Blizzard_SharedXML/Classic/UIDropDownMenuTemplates.xml",
    "Blizzard_SharedXML/TBC/ClassColors.lua",
    "Blizzard_SharedXML/Wrath/SoundKitConstants.lua",
    "Blizzard_FrameXMLBase/Classic/Constants.lua",
    "Blizzard_FrameXMLBase/Classic/FrameLocks.lua",
    "Blizzard_FrameXMLBase/Classic/IconDataProvider.lua",
    "Blizzard_FrameXMLBase/TBC/Localization.lua",
    "Blizzard_FrameXMLBase/Wrath/Constants.lua",
    "Blizzard_FrameXML/Classic/AlertFrameSystems.lua",
    "Blizzard_FrameXML/Classic/AlertFrameSystems.xml",
    "Blizzard_FrameXML/Classic/AlertFrames.lua",
    "Blizzard_FrameXML/Classic/AlertFrames.xml",
    "Blizzard_FrameXML/Classic/ColorPickerFrame.lua",
    "Blizzard_FrameXML/Classic/ColorPickerFrame.xml",
    "Blizzard_FrameXML/Classic/CombatFeedback.lua",
    "Blizzard_BuffFrame/Classic/BuffFrame.lua",
    "Blizzard_GameTooltip/Blizzard_GameTooltip_Classic.toc",
    "Blizzard_GameTooltip/Classic/GameTooltip.lua",
    "Blizzard_GameTooltip/Classic/GameTooltip.xml",
    "Blizzard_ItemButton/Blizzard_ItemButton_Classic.toc",
    "Blizzard_ItemButton/Classic/ItemButtonTemplate.lua",
    "Blizzard_ItemButton/Classic/ItemButtonTemplate.xml",
    "Blizzard_LevelUpDisplay/Cata/LevelUpDisplay.lua",
    "Blizzard_NamePlates/Blizzard_NamePlates.toc",
    "Blizzard_Settings_Shared/Blizzard_Settings_Shared_Classic.toc",
    "Blizzard_Settings_Shared/Classic/AudioOverrides.lua",
    "Blizzard_Settings_Shared/Classic/Blizzard_SettingsPanelTemplates.xml",
    "Blizzard_Settings_Shared/Classic/GraphicsOverrides.lua",
    "Blizzard_UIPanelTemplates/Blizzard_UIPanelTemplates_Classic.toc",
    "Blizzard_UIPanelTemplates/Classic/AutoCastTemplates.lua",
    "Blizzard_UIPanelTemplates/Classic/AutoCastTemplates.xml",
    "Blizzard_UIPanelTemplates/Classic/UIPanelTemplates.lua",
    "Blizzard_UIPanelTemplates/Classic/UIPanelTemplates.xml",
    "Blizzard_UIPanels_Game/Blizzard_UIPanels_Game_Mists.toc",
    "Blizzard_UIPanels_Game/Classic/CastingBarFrame.lua",
    "Blizzard_UIPanels_Game/Classic/CastingBarFrame.xml",
    "Blizzard_UIPanels_Game/Shared/CastingBarFrame.lua",
    "Blizzard_UnitFrame/Cata/EclipseBarFrame.lua",
    "Blizzard_UnitFrame/Cata/EclipseBarFrame.xml",
    "Blizzard_UnitFrame/Cata/RuneFrame.lua",
    "Blizzard_UnitFrame/Cata/RuneFrame.xml",
    "Blizzard_UnitFrame/Classic/ComboFrame.lua",
    "Blizzard_UnitFrame/Classic/ComboFrame.xml",
    "Blizzard_UnitFrame/Classic/CompactUnitFrameOptions.lua",
    "Blizzard_UnitFrame/Classic/Localization.lua",
    "Blizzard_UnitFrame/Classic/PartyFrameTemplates.xml",
    "Blizzard_UnitFrame/Classic/PartyMemberFrame.lua",
    "Blizzard_UnitFrame/Classic/PetFrame.lua",
    "Blizzard_UnitFrame/Classic/PetFrame.xml",
    "Blizzard_UnitFrame/Classic/PlayerFrame.lua",
    "Blizzard_UnitFrame/Classic/PlayerFrame.xml",
    "Blizzard_UnitFrame/Classic/RuneFrame_Shared.lua",
    "Blizzard_UnitFrame/Classic/TargetFrame.lua",
    "Blizzard_UnitFrame/Classic/TargetFrame.xml",
    "Blizzard_UnitFrame/Classic/TotemFrame.lua",
    "Blizzard_UnitFrame/Classic/TotemFrame.xml",
    "Blizzard_UnitFrame/Classic/UnitFrame.lua",
    "Blizzard_UnitFrame/Classic/UnitPowerBarAlt.lua",
    "Blizzard_UnitFrame/Classic/UnitPowerBarAlt.xml",
    "Blizzard_UnitFrame/Mists/AlternatePowerBar.xml",
    "Blizzard_UnitFrame/Mists/MonkHarmonyBar.lua",
    "Blizzard_UnitFrame/Mists/MonkHarmonyBar.xml",
    "Blizzard_UnitFrame/Mists/MonkStaggerBar.lua",
    "Blizzard_UnitFrame/Mists/MonkStaggerBar.xml",
    "Blizzard_UnitFrame/Mists/PaladinPowerBar.lua",
    "Blizzard_UnitFrame/Mists/PaladinPowerBar.xml",
    "Blizzard_UnitFrame/Mists/PriestBar.xml",
    "Blizzard_UnitFrame/Mists/ShardBar.lua",
    "Blizzard_UnitFrame/Mists/ShardBar.xml",
    "Blizzard_UnitFrame/Mists/TotemFrame.lua",
    "Blizzard_UnitFrame/Wrath/AlternatePowerBar.lua",
];

pub(super) fn required_profile_cache_entries() -> &'static [&'static str] {
    match crate::client_profile::ACTIVE {
        crate::client_profile::ClientProfile::Mists => MISTS_REQUIRED_PROFILE_CACHE_ENTRIES,
        _ => &[],
    }
}

pub(super) fn gethe_wow_ui_source_branches() -> &'static [&'static str] {
    match crate::client_profile::ACTIVE {
        crate::client_profile::ClientProfile::Mists => MISTS_GETHE_WOW_UI_SOURCE_BRANCHES,
        _ => DEFAULT_GETHE_WOW_UI_SOURCE_BRANCHES,
    }
}

pub(super) fn cache_entry_is_usable(entry: &str, path: &Path) -> bool {
    match crate::client_profile::ACTIVE {
        crate::client_profile::ClientProfile::Mists => mists_cache_entry_is_usable(entry, path),
        _ => true,
    }
}

fn mists_cache_entry_is_usable(entry: &str, path: &Path) -> bool {
    match entry {
        "Blizzard_ActionBar/Classic/ActionButtonTemplate.xml" => {
            file_contains(path, "ActionBarButtonTemplate")
                && file_contains(path, r#"parentKey="chargeCooldown""#)
        }
        "Blizzard_MicroMenu/Blizzard_MicroMenu_Classic.toc" => file_contains(
            path,
            r#"Cata\MainMenuBarMicroButtons.xml [AllowLoadGameType mists]"#,
        ),
        "Blizzard_MicroMenu/Shared/MicroMenuContainer.lua" => {
            !file_contains(path, "PostAddButtonCallback")
        }
        "Blizzard_NamePlates/Blizzard_NamePlates.toc" => file_contains(
            path,
            "Blizzard_ClassNameplateBar.lua [AllowLoadGameType mainline]",
        ),
        "Blizzard_UIPanels_Game/Shared/CastingBarFrame.lua" => {
            file_contains(path, "function PlayerCastingBarMixin:OnShow()")
        }
        _ => true,
    }
}

fn file_contains(path: &Path, needle: &str) -> bool {
    std::fs::read_to_string(path).is_ok_and(|contents| contents.contains(needle))
}
