//! rilua equivalents of admin_api.rs, admin_api_world.rs,
//! admin_api_mail_premade.rs, admin_combat.rs, and admin_encounter.rs.
//!
//! Registers the `A_Admin` namespace as RustFn closures on rilua's VM.
//! Each function accesses SimState via `borrow_state` / `borrow_state_mut`
//! from `rilua_methods`, using `FromStack` for argument extraction.
//!
//! # generated_stubs.rs approach
//!
//! generated_stubs.rs contains ~962 auto-generated stub functions.
//! These will be regenerated by tools/generate_stubs.py with rilua output
//! rather than converted by hand. See the script for the template.

use crate::lua_api::game_data::{AuraInfo, CastingState, PartyMember, SpellCooldownState, TargetInfo};
use crate::lua_api::rilua_methods::{borrow_state, borrow_state_mut};
use crate::lua_bridge::{FromStack, TableBuilder};
use rilua::vm::state::LuaState;
use rilua::{LuaResult, Val};

// ── Entry point ──────────────────────────────────────────────────────────────

/// Register the `A_Admin` namespace on rilua's global table.
pub fn register_all(lua: &mut rilua::Lua) -> LuaResult<()> {
    use rilua::LuaApiMut;

    let admin_val = {
        let state = lua.state_mut();
        let table = TableBuilder::new(state)
            // Identity
            .set_function("SetPlayerName",         set_player_name)?
            .set_function("SetPlayerClass",        set_player_class)?
            .set_function("SetPlayerRace",         set_player_race)?
            .set_function("SetPlayerLevel",        set_player_level)?
            .set_function("SetPlayerSex",          set_player_sex)?
            // Combat
            .set_function("SetInCombat",           set_in_combat)?
            .set_function("SetResting",            set_resting)?
            .set_function("SetFrameProtected",     set_frame_protected)?
            // Casting & cooldowns
            .set_function("SetCasting",            set_casting)?
            .set_function("StopCasting",           stop_casting)?
            .set_function("SetGCD",                set_gcd)?
            .set_function("SetSpellCooldown",      set_spell_cooldown)?
            // Health & power
            .set_function("SetPlayerHealth",       set_player_health)?
            .set_function("SetPlayerPower",        set_player_power)?
            .set_function("SetTargetHealth",       set_target_health)?
            // Targeting
            .set_function("SetTarget",             set_target)?
            .set_function("ClearTarget",           clear_target)?
            .set_function("SetFocus",              set_focus)?
            .set_function("ClearFocus",            clear_focus)?
            .set_function("SetTargetPower",        set_target_power)?
            .set_function("SetFocusPower",         set_focus_power)?
            .set_function("SetTargetType",         set_target_type)?
            .set_function("SetFocusType",          set_focus_type)?
            .set_function("SetFocusHealth",        set_focus_health)?
            // Party
            .set_function("SetPartySize",          set_party_size)?
            .set_function("SetPartyMember",        set_party_member)?
            .set_function("SetPartyMemberHealth",  set_party_member_health)?
            .set_function("KillPartyMember",       kill_party_member)?
            .set_function("ResPartyMember",        res_party_member)?
            .set_function("SetRotDamage",          set_rot_damage)?
            // Movement
            .set_function("SetMoving",             set_moving)?
            .set_function("SetMounted",            set_mounted)?
            .set_function("SetFlying",             set_flying)?
            .set_function("SetFalling",            set_falling)?
            .set_function("SetSwimming",           set_swimming)?
            // Spec & talents
            .set_function("SetSpec",               set_spec)?
            .set_function("SetTalentRank",         set_talent_rank)?
            .set_function("SetTalentSelection",    set_talent_selection)?
            .set_function("ResetTalents",          reset_talents)?
            // Buffs
            .set_function("AddBuff",               add_buff)?
            .set_function("RemoveBuff",            remove_buff)?
            .set_function("ClearBuffs",            clear_buffs)?
            // Equipment
            .set_function("EquipItem",             equip_item)?
            .set_function("UnequipItem",           unequip_item)?
            // World: zone
            .set_function("SetZone",               set_zone)?
            .set_function("SetSubZone",            set_sub_zone)?
            .set_function("SetInstanceInfo",       set_instance_info)?
            .set_function("SetInInstance",         set_in_instance)?
            // World: economy
            .set_function("SetMoney",              set_money)?
            .set_function("SetItemLevel",          set_item_level)?
            // World: transmog & collections
            .set_function("AddTransmog",           add_transmog)?
            .set_function("RemoveTransmog",        remove_transmog)?
            .set_function("AddTransmogAppearance", add_transmog_appearance)?
            .set_function("SetTransmogForSlot",    set_transmog_for_slot)?
            .set_function("CollectHeirloom",       collect_heirloom)?
            .set_function("UncollectHeirloom",     uncollect_heirloom)?
            .set_function("SetMountCollected",     set_mount_collected)?
            .set_function("SetPetCollected",       set_pet_collected)?
            .set_function("SetToyCollected",       set_toy_collected)?
            .set_function("SetAchievementEarned",  set_achievement_earned)?
            .set_function("HasAchievement",        has_achievement)?
            .set_function("CollectMount",          collect_mount)?
            .set_function("UncollectMount",        uncollect_mount)?
            .set_function("CollectPet",            collect_pet)?
            .set_function("UncollectPet",          uncollect_pet)?
            .set_function("CollectToy",            collect_toy)?
            .set_function("UncollectToy",          uncollect_toy)?
            // World: PvP & guild
            .set_function("SetPvPEnabled",         set_pvp_enabled)?
            .set_function("SetHonorLevel",         set_honor_level)?
            .set_function("SetGuildInfo",          set_guild_info)?
            .set_function("JoinGuild",             join_guild)?
            .set_function("ClearGuild",            clear_guild)?
            .set_function("LeaveGuild",            leave_guild)?
            // World: events
            .set_function("FireEvent",             fire_event_admin)?
            // World: vault
            .set_function("SetVaultActivity",      set_vault_activity)?
            .set_function("SetVaultRewards",       set_vault_rewards)?
            .set_function("ClearVault",            clear_vault)?
            // World: action bars
            .set_function("SetActionSlot",         set_action_slot)?
            .set_function("ClearActionSlot",       clear_action_slot)?
            .set_function("ClearActionBars",       clear_action_bars)?
            // World: bags
            .set_function("AddBagItem",            add_bag_item)?
            .set_function("RemoveBagItem",         remove_bag_item)?
            .set_function("ClearBags",             clear_bags)?
            // Mail
            .set_function("AddMail",               add_mail)?
            .set_function("ClearInbox",            clear_inbox)?
            .set_function("SetInboxCount",         set_inbox_count)?
            // Premade listings
            .set_function("AddPremadeListing",     add_premade_listing)?
            .set_function("ClearPremadeListings",  clear_premade_listings)?
            .set_function("UpdatePremadeListing",  update_premade_listing)?
            // Debug toggles
            .set_function("ToggleDebugBorders",    toggle_debug_borders)?
            .set_function("ToggleDebugAnchors",    toggle_debug_anchors)?
            // Encounter
            .set_function("SimulateBossKill",      simulate_boss_kill)?
            .set_function("StartLootRoll",         start_loot_roll)?
            .set_function("EndLootRoll",           end_loot_roll)?
            // Achievements (fire-event variant)
            .set_function("EarnAchievement",       earn_achievement)?
            .build()
    };

    LuaApiMut::set_global_val(lua, "A_Admin", admin_val)?;
    Ok(())
}

// ── Player identity ──────────────────────────────────────────────────────────

fn set_player_name(state: &mut LuaState) -> LuaResult<u32> {
    let name = String::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.name = name;
    Ok(0)
}

fn set_player_class(state: &mut LuaState) -> LuaResult<u32> {
    let class_index = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.class_index = class_index;
    Ok(0)
}

fn set_player_race(state: &mut LuaState) -> LuaResult<u32> {
    let race_index = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.race_index = race_index as usize;
    Ok(0)
}

fn set_player_level(state: &mut LuaState) -> LuaResult<u32> {
    let level = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.level = level;
    Ok(0)
}

fn set_player_sex(state: &mut LuaState) -> LuaResult<u32> {
    let sex = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.sex = sex;
    Ok(0)
}

// ── Combat ───────────────────────────────────────────────────────────────────

fn set_in_combat(state: &mut LuaState) -> LuaResult<u32> {
    let v = bool::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.in_combat = v;
    Ok(0)
}

fn set_resting(state: &mut LuaState) -> LuaResult<u32> {
    let v = bool::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.is_resting = v;
    Ok(0)
}

fn set_frame_protected(state: &mut LuaState) -> LuaResult<u32> {
    let name = String::from_stack(state, 1)?;
    let v = bool::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    if let Some(id) = st.widgets.get_id_by_name(&name) {
        if let Some(frame) = st.widgets.get_mut(id) {
            frame.is_protected = v;
        }
    }
    Ok(0)
}

// ── Casting & cooldowns ──────────────────────────────────────────────────────

fn set_casting(state: &mut LuaState) -> LuaResult<u32> {
    let spell_id = u32::from_stack(state, 1)?;
    let spell_name = String::from_stack(state, 2)?;
    let icon_path = String::from_stack(state, 3)?;
    let duration = f64::from_stack(state, 4)?;
    let mut st = borrow_state_mut(state)?;
    let now = st.start_time.elapsed().as_secs_f64();
    let cast_id = st.next_cast_id;
    st.next_cast_id += 1;
    st.casting = Some(CastingState {
        spell_id,
        spell_name,
        icon_path,
        start_time: now,
        end_time: now + duration,
        cast_id,
    });
    Ok(0)
}

fn stop_casting(state: &mut LuaState) -> LuaResult<u32> {
    borrow_state_mut(state)?.casting = None;
    Ok(0)
}

fn set_gcd(state: &mut LuaState) -> LuaResult<u32> {
    let duration = f64::from_stack(state, 1)?;
    let mut st = borrow_state_mut(state)?;
    let now = st.start_time.elapsed().as_secs_f64();
    st.gcd = Some((now, duration));
    Ok(0)
}

fn set_spell_cooldown(state: &mut LuaState) -> LuaResult<u32> {
    let spell_id = u32::from_stack(state, 1)?;
    let duration = f64::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    let now = st.start_time.elapsed().as_secs_f64();
    st.spell_cooldowns.insert(
        spell_id,
        SpellCooldownState {
            start: now,
            duration,
        },
    );
    Ok(0)
}

// ── Health & power ───────────────────────────────────────────────────────────

fn set_player_health(state: &mut LuaState) -> LuaResult<u32> {
    let cur = i32::from_stack(state, 1)?;
    let max = i32::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    st.player.health = cur;
    st.player.health_max = max;
    Ok(0)
}

fn set_player_power(state: &mut LuaState) -> LuaResult<u32> {
    let cur = i32::from_stack(state, 1)?;
    let max = i32::from_stack(state, 2)?;
    let power_type = Option::<i32>::from_stack(state, 3)?;
    let mut st = borrow_state_mut(state)?;
    st.player.power = cur;
    st.player.power_max = max;
    if let Some(pt) = power_type {
        st.player.power_type = pt;
    }
    Ok(0)
}

fn set_target_health(state: &mut LuaState) -> LuaResult<u32> {
    let cur = i32::from_stack(state, 1)?;
    let max = i32::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    if let Some(t) = st.current_target.as_mut() {
        t.health = cur;
        t.health_max = max;
    }
    Ok(0)
}

// ── Targeting ────────────────────────────────────────────────────────────────

fn set_target(state: &mut LuaState) -> LuaResult<u32> {
    let name = String::from_stack(state, 1)?;
    let level = i32::from_stack(state, 2)?;
    let class_index = i32::from_stack(state, 3)?;
    let is_enemy = bool::from_stack(state, 4)?;
    let mut st = borrow_state_mut(state)?;
    st.current_target = Some(make_target_info("target", &name, level, class_index, is_enemy));
    Ok(0)
}

fn clear_target(state: &mut LuaState) -> LuaResult<u32> {
    borrow_state_mut(state)?.current_target = None;
    Ok(0)
}

fn set_focus(state: &mut LuaState) -> LuaResult<u32> {
    let name = String::from_stack(state, 1)?;
    let level = i32::from_stack(state, 2)?;
    let class_index = i32::from_stack(state, 3)?;
    let is_enemy = bool::from_stack(state, 4)?;
    let mut st = borrow_state_mut(state)?;
    st.current_focus = Some(make_target_info("focus", &name, level, class_index, is_enemy));
    Ok(0)
}

fn clear_focus(state: &mut LuaState) -> LuaResult<u32> {
    borrow_state_mut(state)?.current_focus = None;
    Ok(0)
}

fn set_target_power(state: &mut LuaState) -> LuaResult<u32> {
    let cur = i32::from_stack(state, 1)?;
    let max = i32::from_stack(state, 2)?;
    let power_type = Option::<i32>::from_stack(state, 3)?;
    let mut st = borrow_state_mut(state)?;
    if let Some(unit) = st.current_target.as_mut() {
        unit.power = cur;
        unit.power_max = max;
        if let Some(pt) = power_type {
            unit.power_type = pt;
        }
    }
    Ok(0)
}

fn set_focus_power(state: &mut LuaState) -> LuaResult<u32> {
    let cur = i32::from_stack(state, 1)?;
    let max = i32::from_stack(state, 2)?;
    let power_type = Option::<i32>::from_stack(state, 3)?;
    let mut st = borrow_state_mut(state)?;
    if let Some(unit) = st.current_focus.as_mut() {
        unit.power = cur;
        unit.power_max = max;
        if let Some(pt) = power_type {
            unit.power_type = pt;
        }
    }
    Ok(0)
}

fn set_target_type(state: &mut LuaState) -> LuaResult<u32> {
    let classification = Option::<String>::from_stack(state, 1)?;
    let creature_type = Option::<String>::from_stack(state, 2)?;
    let reaction = Option::<i32>::from_stack(state, 3)?;
    let mut st = borrow_state_mut(state)?;
    if let Some(unit) = st.current_target.as_mut() {
        if let Some(c) = classification { unit.classification = c; }
        if let Some(ct) = creature_type { unit.creature_type = ct; }
        if let Some(r) = reaction { unit.reaction = r; }
    }
    Ok(0)
}

fn set_focus_type(state: &mut LuaState) -> LuaResult<u32> {
    let classification = Option::<String>::from_stack(state, 1)?;
    let creature_type = Option::<String>::from_stack(state, 2)?;
    let reaction = Option::<i32>::from_stack(state, 3)?;
    let mut st = borrow_state_mut(state)?;
    if let Some(unit) = st.current_focus.as_mut() {
        if let Some(c) = classification { unit.classification = c; }
        if let Some(ct) = creature_type { unit.creature_type = ct; }
        if let Some(r) = reaction { unit.reaction = r; }
    }
    Ok(0)
}

fn set_focus_health(state: &mut LuaState) -> LuaResult<u32> {
    let cur = i32::from_stack(state, 1)?;
    let max = i32::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    if let Some(unit) = st.current_focus.as_mut() {
        unit.health = cur;
        unit.health_max = max;
    }
    Ok(0)
}

// ── Party ─────────────────────────────────────────────────────────────────────

fn set_party_size(state: &mut LuaState) -> LuaResult<u32> {
    let n = i32::from_stack(state, 1)?;
    let size = n.max(0) as usize;
    let mut st = borrow_state_mut(state)?;
    while st.party_members.len() < size {
        st.party_members.push(default_party_member());
    }
    st.party_members.truncate(size);
    Ok(0)
}

fn set_party_member(state: &mut LuaState) -> LuaResult<u32> {
    let idx = i32::from_stack(state, 1)?;
    let name = String::from_stack(state, 2)?;
    let class_index = i32::from_stack(state, 3)?;
    let level = i32::from_stack(state, 4)?;
    let mut st = borrow_state_mut(state)?;
    if let Some(member) = st.party_members.get_mut((idx - 1) as usize) {
        member.name = name;
        member.class_index = class_index;
        member.level = level;
    }
    Ok(0)
}

fn set_party_member_health(state: &mut LuaState) -> LuaResult<u32> {
    let idx = i32::from_stack(state, 1)?;
    let cur = i32::from_stack(state, 2)?;
    let max = i32::from_stack(state, 3)?;
    let mut st = borrow_state_mut(state)?;
    if let Some(member) = st.party_members.get_mut((idx - 1) as usize) {
        member.health = cur;
        member.health_max = max;
    }
    Ok(0)
}

fn kill_party_member(state: &mut LuaState) -> LuaResult<u32> {
    let idx = i32::from_stack(state, 1)?;
    let mut st = borrow_state_mut(state)?;
    if let Some(member) = st.party_members.get_mut((idx - 1) as usize) {
        member.dead_since = Some(std::time::Instant::now());
    }
    Ok(0)
}

fn res_party_member(state: &mut LuaState) -> LuaResult<u32> {
    let idx = i32::from_stack(state, 1)?;
    let mut st = borrow_state_mut(state)?;
    if let Some(member) = st.party_members.get_mut((idx - 1) as usize) {
        member.dead_since = None;
    }
    Ok(0)
}

fn set_rot_damage(state: &mut LuaState) -> LuaResult<u32> {
    let level = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.rot_damage_level = level as usize;
    Ok(0)
}

// ── Movement ──────────────────────────────────────────────────────────────────

fn set_moving(state: &mut LuaState) -> LuaResult<u32> {
    let v = bool::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.movement.moving = v;
    Ok(0)
}

fn set_mounted(state: &mut LuaState) -> LuaResult<u32> {
    let v = bool::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.movement.mounted = v;
    Ok(0)
}

fn set_flying(state: &mut LuaState) -> LuaResult<u32> {
    let v = bool::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.movement.flying = v;
    Ok(0)
}

fn set_falling(state: &mut LuaState) -> LuaResult<u32> {
    let v = bool::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.movement.falling = v;
    Ok(0)
}

fn set_swimming(state: &mut LuaState) -> LuaResult<u32> {
    let v = bool::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.movement.swimming = v;
    Ok(0)
}

// ── Spec & talents ────────────────────────────────────────────────────────────

fn set_spec(state: &mut LuaState) -> LuaResult<u32> {
    let spec_index = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.active_spec_index = spec_index;
    Ok(0)
}

fn set_talent_rank(state: &mut LuaState) -> LuaResult<u32> {
    let node_id = u32::from_stack(state, 1)?;
    let rank = u32::from_stack(state, 2)?;
    borrow_state_mut(state)?.talents.set_node_rank(node_id, rank);
    Ok(0)
}

fn set_talent_selection(state: &mut LuaState) -> LuaResult<u32> {
    let node_id = u32::from_stack(state, 1)?;
    let entry_id = u32::from_stack(state, 2)?;
    borrow_state_mut(state)?.talents.set_node_selection(node_id, Some(entry_id));
    Ok(0)
}

fn reset_talents(state: &mut LuaState) -> LuaResult<u32> {
    let mut st = borrow_state_mut(state)?;
    st.talents.clear_ranks();
    st.talents.node_selections.clear();
    st.talents.active_hero_subtree_id = None;
    Ok(0)
}

// ── Buffs ─────────────────────────────────────────────────────────────────────

fn add_buff(state: &mut LuaState) -> LuaResult<u32> {
    let spell_id = i32::from_stack(state, 1)?;
    let name = String::from_stack(state, 2)?;
    let icon = String::from_stack(state, 3)?;
    let duration = f64::from_stack(state, 4)?;
    let stacks = i32::from_stack(state, 5)?;
    let mut st = borrow_state_mut(state)?;
    let buff = build_admin_buff(&st, spell_id, name, icon, duration, stacks);
    st.player.buffs.push(buff);
    Ok(0)
}

fn remove_buff(state: &mut LuaState) -> LuaResult<u32> {
    let spell_id = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.buffs.retain(|a| a.spell_id != spell_id);
    Ok(0)
}

fn clear_buffs(state: &mut LuaState) -> LuaResult<u32> {
    borrow_state_mut(state)?.player.buffs.clear();
    Ok(0)
}

// ── Equipment ─────────────────────────────────────────────────────────────────

fn equip_item(state: &mut LuaState) -> LuaResult<u32> {
    use crate::lua_api::state_types::{CharacterStats, EquippedItem};
    let slot = i32::from_stack(state, 1)?;
    let item_id = u32::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    st.player.equipped_items.insert(
        slot,
        EquippedItem { item_id, enchant_id: 0, gem_ids: [0, 0, 0] },
    );
    st.player.stats = CharacterStats::compute(&st.player.equipped_items, st.player.class_index);
    Ok(0)
}

fn unequip_item(state: &mut LuaState) -> LuaResult<u32> {
    use crate::lua_api::state_types::CharacterStats;
    let slot = i32::from_stack(state, 1)?;
    let mut st = borrow_state_mut(state)?;
    st.player.equipped_items.remove(&slot);
    st.player.stats = CharacterStats::compute(&st.player.equipped_items, st.player.class_index);
    Ok(0)
}

// ── Zone ──────────────────────────────────────────────────────────────────────

fn set_zone(state: &mut LuaState) -> LuaResult<u32> {
    let name = String::from_stack(state, 1)?;
    let id = i32::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    st.world.zone_name = name;
    st.world.zone_id = id;
    Ok(0)
}

fn set_sub_zone(state: &mut LuaState) -> LuaResult<u32> {
    let name = String::from_stack(state, 1)?;
    borrow_state_mut(state)?.world.sub_zone_name = name;
    Ok(0)
}

fn set_instance_info(state: &mut LuaState) -> LuaResult<u32> {
    let name = String::from_stack(state, 1)?;
    let inst_type = String::from_stack(state, 2)?;
    let difficulty = i32::from_stack(state, 3)?;
    let max_players = i32::from_stack(state, 4)?;
    let mut st = borrow_state_mut(state)?;
    st.world.instance_name = name;
    st.world.instance_type = inst_type;
    st.world.instance_difficulty = difficulty;
    st.world.instance_max_players = max_players;
    st.world.in_instance = true;
    Ok(0)
}

fn set_in_instance(state: &mut LuaState) -> LuaResult<u32> {
    let v = bool::from_stack(state, 1)?;
    borrow_state_mut(state)?.world.in_instance = v;
    Ok(0)
}

// ── Economy ───────────────────────────────────────────────────────────────────

fn set_money(state: &mut LuaState) -> LuaResult<u32> {
    let copper = i64::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.money = copper;
    Ok(0)
}

fn set_item_level(state: &mut LuaState) -> LuaResult<u32> {
    let ilvl = f64::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.item_level = ilvl as f32;
    Ok(0)
}

// ── Transmog & collections ────────────────────────────────────────────────────

fn add_transmog(state: &mut LuaState) -> LuaResult<u32> {
    let id = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.world.collected_transmogs.insert(id);
    Ok(0)
}

fn remove_transmog(state: &mut LuaState) -> LuaResult<u32> {
    let id = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.world.collected_transmogs.remove(&id);
    Ok(0)
}

fn add_transmog_appearance(state: &mut LuaState) -> LuaResult<u32> {
    use crate::lua_api::state_types::TransmogAppearance;
    let source_id = i32::from_stack(state, 1)?;
    let category_id = i32::from_stack(state, 2)?;
    let item_id = i32::from_stack(state, 3)?;
    let mut st = borrow_state_mut(state)?;
    let visual_id = st.world.transmog_appearances.iter().map(|a| a.visual_id).max().unwrap_or(0) + 1;
    st.world.transmog_appearances.push(TransmogAppearance {
        source_id,
        visual_id,
        category_id,
        item_id,
        is_collected: true,
        source_type: 0,
        item_mod_id: 0,
    });
    Ok(0)
}

fn set_transmog_for_slot(state: &mut LuaState) -> LuaResult<u32> {
    let slot_id = i32::from_stack(state, 1)?;
    let source_id = i32::from_stack(state, 2)?;
    borrow_state_mut(state)?.world.applied_transmog_slots.insert(slot_id, source_id);
    Ok(0)
}

fn collect_heirloom(state: &mut LuaState) -> LuaResult<u32> {
    let item_id = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.world.collected_heirlooms.insert(item_id as u32);
    Ok(0)
}

fn uncollect_heirloom(state: &mut LuaState) -> LuaResult<u32> {
    let item_id = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.world.collected_heirlooms.remove(&(item_id as u32));
    Ok(0)
}

fn set_mount_collected(state: &mut LuaState) -> LuaResult<u32> {
    let id = i32::from_stack(state, 1)?;
    let collected = bool::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    if collected { st.world.collected_mounts.insert(id); } else { st.world.collected_mounts.remove(&id); }
    Ok(0)
}

fn set_pet_collected(state: &mut LuaState) -> LuaResult<u32> {
    let id = i32::from_stack(state, 1)?;
    let collected = bool::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    if collected { st.world.collected_pets.insert(id); } else { st.world.collected_pets.remove(&id); }
    Ok(0)
}

fn set_toy_collected(state: &mut LuaState) -> LuaResult<u32> {
    let id = i32::from_stack(state, 1)?;
    let collected = bool::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    if collected { st.world.collected_toys.insert(id); } else { st.world.collected_toys.remove(&id); }
    Ok(0)
}

fn set_achievement_earned(state: &mut LuaState) -> LuaResult<u32> {
    let id = i32::from_stack(state, 1)?;
    let collected = bool::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    if collected { st.world.earned_achievements.insert(id); } else { st.world.earned_achievements.remove(&id); }
    Ok(0)
}

fn has_achievement(state: &mut LuaState) -> LuaResult<u32> {
    let id = i32::from_stack(state, 1)?;
    let result = borrow_state(state)?.world.earned_achievements.contains(&id);
    state.push(Val::Bool(result));
    Ok(1)
}

fn earn_achievement(state: &mut LuaState) -> LuaResult<u32> {
    use crate::event::{Event, EventArg};
    let id = i32::from_stack(state, 1)?;
    let mut st = borrow_state_mut(state)?;
    st.world.earned_achievements.insert(id);
    st.events.push(Event {
        name: "ACHIEVEMENT_EARNED".to_string(),
        args: vec![EventArg::Number(id as f64)],
    });
    Ok(0)
}

fn collect_mount(state: &mut LuaState) -> LuaResult<u32> {
    let mount_id = u32::from_stack(state, 1)?;
    let mut st = borrow_state_mut(state)?;
    st.world.collected_mounts.insert(mount_id as i32);
    if let Some(m) = st.world.mounts.iter_mut().find(|m| m.mount_id == mount_id) {
        m.is_collected = true;
        m.is_usable = true;
    }
    Ok(0)
}

fn uncollect_mount(state: &mut LuaState) -> LuaResult<u32> {
    let mount_id = u32::from_stack(state, 1)?;
    let mut st = borrow_state_mut(state)?;
    st.world.collected_mounts.remove(&(mount_id as i32));
    if let Some(m) = st.world.mounts.iter_mut().find(|m| m.mount_id == mount_id) {
        m.is_collected = false;
        m.is_usable = false;
    }
    Ok(0)
}

fn collect_pet(state: &mut LuaState) -> LuaResult<u32> {
    let species_id = u32::from_stack(state, 1)?;
    let mut st = borrow_state_mut(state)?;
    st.world.collected_pets.insert(species_id as i32);
    if let Some(p) = st.world.pets.iter_mut().find(|p| p.species_id == species_id) {
        p.is_collected = true;
    }
    Ok(0)
}

fn uncollect_pet(state: &mut LuaState) -> LuaResult<u32> {
    let species_id = u32::from_stack(state, 1)?;
    let mut st = borrow_state_mut(state)?;
    st.world.collected_pets.remove(&(species_id as i32));
    if let Some(p) = st.world.pets.iter_mut().find(|p| p.species_id == species_id) {
        p.is_collected = false;
    }
    Ok(0)
}

fn collect_toy(state: &mut LuaState) -> LuaResult<u32> {
    let item_id = u32::from_stack(state, 1)?;
    let mut st = borrow_state_mut(state)?;
    st.world.collected_toys.insert(item_id as i32);
    if let Some(toy) = st.world.toys.iter_mut().find(|t| t.item_id == item_id) {
        toy.is_collected = true;
        toy.is_usable = true;
    }
    Ok(0)
}

fn uncollect_toy(state: &mut LuaState) -> LuaResult<u32> {
    let item_id = u32::from_stack(state, 1)?;
    let mut st = borrow_state_mut(state)?;
    st.world.collected_toys.remove(&(item_id as i32));
    if let Some(toy) = st.world.toys.iter_mut().find(|t| t.item_id == item_id) {
        toy.is_collected = false;
        toy.is_usable = false;
    }
    Ok(0)
}

// ── PvP & guild ───────────────────────────────────────────────────────────────

fn set_pvp_enabled(state: &mut LuaState) -> LuaResult<u32> {
    let v = bool::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.pvp_enabled = v;
    Ok(0)
}

fn set_honor_level(state: &mut LuaState) -> LuaResult<u32> {
    let level = i32::from_stack(state, 1)?;
    borrow_state_mut(state)?.player.honor_level = level;
    Ok(0)
}

fn set_guild_info(state: &mut LuaState) -> LuaResult<u32> {
    let name = String::from_stack(state, 1)?;
    let rank = String::from_stack(state, 2)?;
    let num_members = i32::from_stack(state, 3)?;
    let mut st = borrow_state_mut(state)?;
    st.world.guild_name = Some(name);
    st.world.guild_rank = Some(rank);
    st.world.guild_num_members = num_members;
    Ok(0)
}

fn join_guild(state: &mut LuaState) -> LuaResult<u32> {
    use crate::event::{Event, EventArg};
    let name = String::from_stack(state, 1)?;
    let rank = String::from_stack(state, 2)?;
    let num_members = i32::from_stack(state, 3)?;
    let mut st = borrow_state_mut(state)?;
    st.world.guild_name = Some(name);
    st.world.guild_rank = Some(rank);
    st.world.guild_num_members = num_members;
    st.events.push(Event { name: "PLAYER_GUILD_UPDATE".to_string(), args: vec![] });
    Ok(0)
}

fn clear_guild(state: &mut LuaState) -> LuaResult<u32> {
    let mut st = borrow_state_mut(state)?;
    st.world.guild_name = None;
    st.world.guild_rank = None;
    st.world.guild_num_members = 0;
    Ok(0)
}

fn leave_guild(state: &mut LuaState) -> LuaResult<u32> {
    use crate::event::{Event, EventArg};
    let mut st = borrow_state_mut(state)?;
    st.world.guild_name = None;
    st.world.guild_rank = None;
    st.world.guild_num_members = 0;
    st.events.push(Event { name: "PLAYER_GUILD_UPDATE".to_string(), args: vec![] });
    Ok(0)
}

// ── Events ────────────────────────────────────────────────────────────────────

fn fire_event_admin(state: &mut LuaState) -> LuaResult<u32> {
    use crate::event::{Event, EventArg};
    use crate::lua_bridge::stack_val;

    let event_name = String::from_stack(state, 1)?;
    let nargs = state.top() - state.base as i32;
    let mut event_args = Vec::new();
    for i in 2..=nargs {
        let val = stack_val(state, i);
        event_args.push(lua_val_to_event_arg(state, val));
    }
    borrow_state_mut(state)?.events.push(Event { name: event_name, args: event_args });
    Ok(0)
}

// ── Debug toggles ─────────────────────────────────────────────────────────────

fn toggle_debug_borders(state: &mut LuaState) -> LuaResult<u32> {
    let mut st = borrow_state_mut(state)?;
    st.debug_borders = !st.debug_borders;
    st.invalidate_strata_buckets();
    let result = st.debug_borders;
    drop(st);
    state.push(Val::Bool(result));
    Ok(1)
}

fn toggle_debug_anchors(state: &mut LuaState) -> LuaResult<u32> {
    let mut st = borrow_state_mut(state)?;
    st.debug_anchors = !st.debug_anchors;
    st.invalidate_strata_buckets();
    let result = st.debug_anchors;
    drop(st);
    state.push(Val::Bool(result));
    Ok(1)
}

// ── Vault ─────────────────────────────────────────────────────────────────────

fn set_vault_activity(state: &mut LuaState) -> LuaResult<u32> {
    use crate::lua_api::state::GreatVaultActivity;
    let atype = i32::from_stack(state, 1)?;
    let index = i32::from_stack(state, 2)?;
    let threshold = i32::from_stack(state, 3)?;
    let progress = i32::from_stack(state, 4)?;
    let level = i32::from_stack(state, 5)?;
    let activity = GreatVaultActivity { activity_type: atype, index, threshold, progress, level };
    let mut st = borrow_state_mut(state)?;
    if let Some(existing) = st.world.great_vault_activities.iter_mut()
        .find(|a| a.activity_type == atype && a.index == index)
    {
        *existing = activity;
    } else {
        st.world.great_vault_activities.push(activity);
    }
    Ok(0)
}

fn set_vault_rewards(state: &mut LuaState) -> LuaResult<u32> {
    let has = bool::from_stack(state, 1)?;
    let can_claim = Option::<bool>::from_stack(state, 2)?;
    let mut st = borrow_state_mut(state)?;
    st.world.great_vault_has_rewards = has;
    st.world.great_vault_can_claim = can_claim.unwrap_or(has);
    Ok(0)
}

fn clear_vault(state: &mut LuaState) -> LuaResult<u32> {
    let mut st = borrow_state_mut(state)?;
    st.world.great_vault_activities.clear();
    st.world.great_vault_has_rewards = false;
    st.world.great_vault_can_claim = false;
    Ok(0)
}

// ── Action bars ───────────────────────────────────────────────────────────────

fn set_action_slot(state: &mut LuaState) -> LuaResult<u32> {
    let slot = u32::from_stack(state, 1)?;
    let spell_id = u32::from_stack(state, 2)?;
    borrow_state_mut(state)?.action_bars.insert(slot, spell_id);
    Ok(0)
}

fn clear_action_slot(state: &mut LuaState) -> LuaResult<u32> {
    let slot = u32::from_stack(state, 1)?;
    borrow_state_mut(state)?.action_bars.remove(&slot);
    Ok(0)
}

fn clear_action_bars(state: &mut LuaState) -> LuaResult<u32> {
    borrow_state_mut(state)?.action_bars.clear();
    Ok(0)
}

// ── Bags ──────────────────────────────────────────────────────────────────────

fn add_bag_item(state: &mut LuaState) -> LuaResult<u32> {
    use crate::lua_api::state::BagItem;
    let bag = i32::from_stack(state, 1)?;
    let slot = i32::from_stack(state, 2)?;
    let item_id = u32::from_stack(state, 3)?;
    let stack = Option::<i32>::from_stack(state, 4)?;
    borrow_state_mut(state)?.bag_items.insert(
        (bag, slot),
        BagItem { item_id, stack_count: stack.unwrap_or(1) },
    );
    Ok(0)
}

fn remove_bag_item(state: &mut LuaState) -> LuaResult<u32> {
    let bag = i32::from_stack(state, 1)?;
    let slot = i32::from_stack(state, 2)?;
    borrow_state_mut(state)?.bag_items.remove(&(bag, slot));
    Ok(0)
}

fn clear_bags(state: &mut LuaState) -> LuaResult<u32> {
    borrow_state_mut(state)?.bag_items.clear();
    Ok(0)
}

// ── Mail ──────────────────────────────────────────────────────────────────────

fn add_mail(state: &mut LuaState) -> LuaResult<u32> {
    use crate::lua_bridge::stack_val;

    let sender = opt_string_stack(state, 1, "Unknown");
    let subject = opt_string_stack(state, 2, "No Subject");
    let body = opt_string_stack(state, 3, "");
    let money = match stack_val(state, 4) {
        Val::Num(n) => n as u64,
        _ => 0,
    };
    // items table at arg 5 — parsed as empty for now (no mlua Table access in rilua path)
    let items = Vec::new();

    let mut st = borrow_state_mut(state)?;
    let id = st.player.next_mail_id;
    st.player.next_mail_id += 1;
    st.player.inbox.push(build_mail(id, sender, subject, body, money, items));
    Ok(0)
}

fn clear_inbox(state: &mut LuaState) -> LuaResult<u32> {
    borrow_state_mut(state)?.player.inbox.clear();
    Ok(0)
}

fn set_inbox_count(state: &mut LuaState) -> LuaResult<u32> {
    let count = i32::from_stack(state, 1)?;
    let mut st = borrow_state_mut(state)?;
    st.player.inbox.clear();
    for i in 0..count {
        let id = st.player.next_mail_id;
        st.player.next_mail_id += 1;
        let sender = format!("Player{}", i + 1);
        let subject = format!("Test Mail #{}", i + 1);
        let body = format!("This is test mail message {}.", i + 1);
        st.player.inbox.push(build_mail(id, sender, subject, body, 0, Vec::new()));
    }
    Ok(0)
}

// ── Premade listings ──────────────────────────────────────────────────────────

fn add_premade_listing(state: &mut LuaState) -> LuaResult<u32> {
    use crate::lua_api::state_types::PremadeListing;
    let name = String::from_stack(state, 1)?;
    let comment = String::from_stack(state, 2)?;
    let activity_id = u32::from_stack(state, 3)?;
    let num = i32::from_stack(state, 4)?;
    let max = i32::from_stack(state, 5)?;
    let mut st = borrow_state_mut(state)?;
    let id = st.world.premade_listings.len() as u32 + 1;
    st.world.premade_listings.push(PremadeListing {
        search_result_id: id,
        name,
        comment,
        leader_name: "Player".to_string(),
        activity_id,
        num_members: num,
        max_members: max,
        voice_chat: false,
        auto_accept: false,
        is_delisted: false,
    });
    drop(st);
    state.push(Val::Num(id as f64));
    Ok(1)
}

fn clear_premade_listings(state: &mut LuaState) -> LuaResult<u32> {
    borrow_state_mut(state)?.world.premade_listings.clear();
    Ok(0)
}

fn update_premade_listing(state: &mut LuaState) -> LuaResult<u32> {
    use crate::lua_bridge::stack_val;
    let result_id = u32::from_stack(state, 1)?;
    let field = String::from_stack(state, 2)?;
    let value = stack_val(state, 3);
    let mut st = borrow_state_mut(state)?;
    let Some(listing) = st.world.premade_listings.iter_mut()
        .find(|l| l.search_result_id == result_id)
    else {
        return Ok(0);
    };
    match field.as_str() {
        "numMembers" => {
            if let Val::Num(n) = value { listing.num_members = n as i32; }
        }
        "isDelisted" => {
            if let Val::Bool(b) = value { listing.is_delisted = b; }
        }
        _ => {}
    }
    Ok(0)
}

// ── Encounter ─────────────────────────────────────────────────────────────────

fn simulate_boss_kill(state: &mut LuaState) -> LuaResult<u32> {
    use crate::event::{Event, EventArg};
    let encounter_id = i32::from_stack(state, 1)?;
    let name = String::from_stack(state, 2)?;
    let difficulty_id = i32::from_stack(state, 3)?;
    let group_size = i32::from_stack(state, 4)?;
    let mut st = borrow_state_mut(state)?;
    st.events.push(Event {
        name: "ENCOUNTER_END".to_string(),
        args: vec![
            EventArg::Number(encounter_id as f64),
            EventArg::String(name.clone()),
            EventArg::Number(difficulty_id as f64),
            EventArg::Number(group_size as f64),
            EventArg::Number(1.0), // success
        ],
    });
    st.events.push(Event {
        name: "BOSS_KILL".to_string(),
        args: vec![
            EventArg::Number(encounter_id as f64),
            EventArg::String(name),
        ],
    });
    Ok(0)
}

fn start_loot_roll(state: &mut LuaState) -> LuaResult<u32> {
    use crate::event::{Event, EventArg};
    use crate::lua_api::state::LootRollInfo;
    use crate::lua_bridge::stack_val;

    let roll_id = i32::from_stack(state, 1)?;
    let roll_time = f64::from_stack(state, 2)?;
    let item_name = opt_string_stack(state, 3, "");
    let item_texture = opt_string_stack(state, 4, "");
    let item_quality = match stack_val(state, 5) { Val::Num(n) => n as i32, _ => 4 };
    let item_level = match stack_val(state, 6) { Val::Num(n) => n as i32, _ => 0 };
    let item_link = opt_string_stack(state, 7, "");

    let info = LootRollInfo {
        roll_id,
        roll_time,
        texture: item_texture,
        name: item_name,
        count: 1,
        quality: item_quality,
        bind_on_pickup: true,
        can_need: true,
        can_greed: true,
        can_disenchant: false,
        disenchant_level: 0,
        item_level,
        item_link,
    };
    let mut st = borrow_state_mut(state)?;
    st.world.loot_rolls.insert(roll_id, info);
    st.events.push(Event {
        name: "START_LOOT_ROLL".to_string(),
        args: vec![EventArg::Number(roll_id as f64), EventArg::Number(roll_time)],
    });
    Ok(0)
}

fn end_loot_roll(state: &mut LuaState) -> LuaResult<u32> {
    use crate::event::{Event, EventArg};
    let roll_id = i32::from_stack(state, 1)?;
    let mut st = borrow_state_mut(state)?;
    st.world.loot_rolls.remove(&roll_id);
    st.events.push(Event {
        name: "LOOT_ROLLS_COMPLETE".to_string(),
        args: vec![EventArg::Number(roll_id as f64)],
    });
    Ok(0)
}

// ── Internal helpers ──────────────────────────────────────────────────────────

/// Build a TargetInfo with default fields from admin-supplied parameters.
fn make_target_info(
    unit_id: &str,
    name: &str,
    level: i32,
    class_index: i32,
    is_enemy: bool,
) -> TargetInfo {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.subsec_nanos())
        .unwrap_or(0);
    let guid = if is_enemy {
        format!("Creature-0-0-0-0-0-{}", nanos % 1_000_000)
    } else {
        format!("Player-0000-{:08}", nanos % 100_000_000)
    };
    TargetInfo {
        unit_id: unit_id.to_string(),
        name: name.to_string(),
        class_index,
        level,
        health: 100_000,
        health_max: 100_000,
        power: 50_000,
        power_max: 100_000,
        power_type: 0,
        power_type_name: "MANA".to_string(),
        is_player: !is_enemy,
        is_enemy,
        guid,
        classification: "normal".to_string(),
        creature_type: "Humanoid".to_string(),
        reaction: if is_enemy { 2 } else { 5 },
    }
}

/// Build a default party member for padding.
fn default_party_member() -> PartyMember {
    PartyMember {
        name: "Unknown".to_string(),
        class_index: 1,
        level: 80,
        health: 100_000,
        health_max: 100_000,
        power: 0,
        power_max: 100,
        power_type: 1,
        power_type_name: "RAGE".to_string(),
        is_leader: false,
        dead_since: None,
    }
}

/// Build an AuraInfo for admin-added buffs.
fn build_admin_buff(
    st: &crate::lua_api::state::SimState,
    spell_id: i32,
    name: String,
    icon: String,
    duration: f64,
    stacks: i32,
) -> AuraInfo {
    let expiration_time = if duration > 0.0 {
        st.start_time.elapsed().as_secs_f64() + duration
    } else {
        0.0
    };
    AuraInfo {
        name,
        spell_id,
        icon: icon.parse::<i32>().unwrap_or(0),
        duration,
        expiration_time,
        applications: stacks,
        source_unit: "player".to_string(),
        is_helpful: true,
        is_stealable: false,
        can_apply_aura: true,
        is_from_player_or_player_pet: true,
        aura_instance_id: (st.player.buffs.len() + 1) as i32,
    }
}

/// Build a MailMessage for admin inbox functions.
fn build_mail(
    id: u64,
    sender: String,
    subject: String,
    body: String,
    money: u64,
    items: Vec<crate::lua_api::state_types::MailAttachment>,
) -> crate::lua_api::state_types::MailMessage {
    crate::lua_api::state_types::MailMessage {
        id,
        sender,
        subject,
        body,
        money,
        cod_amount: 0,
        items,
        days_left: 30.0,
        was_read: false,
        was_returned: false,
        can_reply: true,
        is_gm: false,
        stationery_icon: 0,
    }
}

/// Convert a rilua `Val` to an `EventArg`.
fn lua_val_to_event_arg(state: &LuaState, val: Val) -> crate::event::EventArg {
    use crate::event::EventArg;
    match val {
        Val::Str(s) => {
            let text = state.gc.string_arena.get(s)
                .map(|ls| String::from_utf8_lossy(ls.data()).into_owned())
                .unwrap_or_default();
            EventArg::String(text)
        }
        Val::Num(n) => EventArg::Number(n),
        Val::Bool(b) => EventArg::Boolean(b),
        _ => EventArg::Nil,
    }
}

/// Extract a string from the stack, returning a default if nil or absent.
fn opt_string_stack(state: &LuaState, index: i32, default: &str) -> String {
    match crate::lua_bridge::stack_val(state, index) {
        Val::Str(s) => state.gc.string_arena.get(s)
            .map(|ls| String::from_utf8_lossy(ls.data()).into_owned())
            .unwrap_or_else(|| default.to_string()),
        _ => default.to_string(),
    }
}
