//! Valid WoW event names A-G tail (split for file-length limits).
//! Sorted for membership checks.

pub const EVENTS_A_TAIL: &[&str] = &[
    "GUILD_CHALLENGE_COMPLETED",
    "GUILD_CHALLENGE_UPDATED",
    "GUILD_EVENT_LOG_UPDATE",
    "GUILD_INVITE_CANCEL",
    "GUILD_INVITE_REQUEST",
    "GUILD_MOTD",
    "GUILD_NEWS_UPDATE",
    "GUILD_PARTY_STATE_UPDATED",
    "GUILD_RANKS_UPDATE",
    "GUILD_RECIPE_KNOWN_BY_MEMBERS",
    "GUILD_REGISTRAR_CLOSED",
    "GUILD_REGISTRAR_SHOW",
    "GUILD_RENAME_NAME_CHECK",
    "GUILD_RENAME_REFUND_RESULT",
    "GUILD_RENAME_REQUIRED",
    "GUILD_RENAME_STATUS_UPDATE",
    "GUILD_REWARDS_LIST",
    "GUILD_REWARDS_LIST_UPDATE",
    "GUILD_ROSTER_UPDATE",
    "GUILD_TRADESKILL_UPDATE",
    "GX_RESTARTED",
];
