name: Test

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use CI cargo config
        run: cp .cargo/config.ci.toml .cargo/config.toml

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo test
        run: cargo test --no-default-features
